name: Job Scraper

on:
  schedule:
    - cron: '*/15 * * * *'  # Se ejecuta cada 15 minutos
  workflow_dispatch:        # Permite ejecuciones manuales

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'  # Especifica tu versión de Python

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          python -m pip install -r requirements.txt
        else
          echo "No requirements.txt found, skipping..."
        fi


    - name: Run Scraper
      run: |
        python app.py

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Job Scraper Run - ${{ github.workflow }} #${{ github.run_number }}"
        body: |
          Hola,

          El workflow de Job Scraper ha finalizado.

          **Estado:** ${{ job.status }}
          **Repositorio:** ${{ github.repository }}
          **ID de Ejecución:** ${{ github.run_id }}
          **Número de Ejecución:** ${{ github.run_number }}
          **URL de Ejecución:** ${{ github.run_url }}

          Saludos cordiales,
          GitHub Actions
        from: ${{ secrets.EMAIL_FROM }}
        to: ${{ secrets.EMAIL_TO }}
        secure: true
